#!/bin/sh
#
# Automatic update for Flashfore Adventurer 5M MCUs in Klipper Mod.
#

UPDATE_SCRIPT="/usr/libexec/mcu_update.sh"

start() {
    if ! $UPDATE_SCRIPT check_update
    then

        echo "Starting MCU update ..."
        xzcat /usr/share/klipper_mod/fb/mcu_update.img.xz > /dev/fb0

        if $UPDATE_SCRIPT update
        then
            xzcat /usr/share/klipper_mod/fb/mcu_update_ok.img.xz > /dev/fb0
        else
            xzcat /usr/share/klipper_mod/fb/mcu_update_error.img.xz > /dev/fb0
            # create marker file to abort init sequence
            touch /run/init_break
        fi

    fi
}

case "$1" in
  start)
        start
        ;;
  stop)
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit $?
