#!/bin/sh
#
# Start klipperscreen
#

KLIPPERSCREEN_SCRIPT=/root/printer_software/KlipperScreen/start.sh
PID_FILE=/run/klipperscreen.pid
KLIPPERSCREEN_NICENESS=2

start() {
    # goto the dir to execute the script
    cd $KLIPPERSCREEN_DIR
    start-stop-daemon -S -b -m -p $PID_FILE -N $KLIPPERSCREEN_NICENESS --exec /bin/sh -- -c $KLIPPERSCREEN_SCRIPT
}

stop() {
    start-stop-daemon -K -q -p $PID_FILE
}

restart() {
    stop
    sleep 2
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
