#!/bin/sh
#
# Start klipperscreen
#
PYTHON=/usr/bin/python3
KLIPPERSCREEN=/opt/klipperscreen/screen.py
PID_FILE=/run/klipperscreen.pid
KLIPPERSCREEN_NICENESS=2

start() {
    # fix loaders, if they were not created correctly during the system build.
    /usr/bin/gdk-pixbuf-query-loaders > /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
    
    export DISPLAY=:0
    export HOME=/root
    
    start-stop-daemon -S -b -m -p $PID_FILE -N $KLIPPERSCREEN_NICENESS --exec $PYTHON $KLIPPERSCREEN
}

stop() {
    start-stop-daemon -K -q -p $PID_FILE
}

restart() {
    stop
    sleep 2
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
