#!/bin/sh
#
# Start klipperscreen
#

KLIPPERSCREEN_SCRIPT=/root/printer_software/KlipperScreen/start.sh
PID_FILE=/run/klipperscreen.pid
KLIPPERSCREEN_NICENESS=2

start() {
    # fix loaders, for now we do this dynamicly, can problable be moved to a overlay file
    /usr/bin/gdk-pixbuf-query-loaders > /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
    # goto the dir to execute the script
    cd $KLIPPERSCREEN_DIR
    start-stop-daemon -S -b -m -p $PID_FILE -N $KLIPPERSCREEN_NICENESS --exec /bin/sh -- -c $KLIPPERSCREEN_SCRIPT
}

stop() {
    start-stop-daemon -K -q -p $PID_FILE
}

restart() {
    stop
    sleep 2
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
