#!/bin/sh
#
# Start guppyscreen
#

GUPPYSCREEN=/opt/guppyscreen/guppyscreen
PID_FILE=/run/guppyscreen.pid
NICENESS=10

start() {
    # set backlight to 0% first, the LCD values are not initialized properly
    # which is done when disable/enable is triggered. Otherwise
    # 1% would be 100% and 100% would be 1%
    backlight 0%
    backlight 75%

    start-stop-daemon -S -b -m -p $PID_FILE -N $NICENESS --exec /bin/sh -- -c $GUPPYSCREEN
}

stop() {
    start-stop-daemon -K -q -p $PID_FILE
}

restart() {
    stop
    sleep 2
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
