#!/bin/sh
#
# Starts busybox ntpd to sync time and keep fake-hwclock up to date.
#
NTP_SERVER="pool.ntp.org"
PID_FILE=/run/ntpd.pid

start() {
	printf "Starting busybox ntpd: "
	start-stop-daemon -S -b -m -p $PID_FILE --exec /usr/sbin/ntpd -- -n -S fake-hwclock -p $NTP_SERVER
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping busybox ntpd: "
	start-stop-daemon -K -q -p $PID_FILE
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
