#!/bin/sh
#
# Show mod start screen on framebuffer.
#

start() {
    xzcat /usr/share/klipper_mod/fb/mod_start.img.xz > /dev/fb0
}

case "$1" in
  start)
        start
        ;;
  stop)
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit $?
